In [ ]:
import xlrd 
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import matplotlib.pyplot as plt
import keras

from keras.models import Sequential,model_from_json
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop
import pylab as plt



# Setting Path of File and Initializing List:
location = ("UNB_binary_sep.xlsx") 
list1 = []

# Opening the Workbook and Defining Which Sheet to Use:
wb = xlrd.open_workbook(location) 
sheet = wb.sheet_by_index(0) 

# Starting at Row 0 and Column 0:
sheet.cell_value(0, 0)

rows, cols = (165367, 10) 

# Iterating Over the Number of Rows and Appending to List:
for i in range(0, rows):
    list1.append(sheet.row_values(i))



#maximum lengh of word in list in every row 
maxl = []
for i in range(1,rows):
    max1=0
    for j in range(cols):
        sr1=list1[i][j]
        if(type(sr1)==float):
          max1=1
        elif(type(sr1)==int):
          max1=1
        else:
            ml1=len(list1[i][j])
            if(ml1>max1):
                max1=ml1 
    maxl.append(max1)

#length of domain name
len_dom= []
for i in range(1,rows):
    sr1=list1[i][1]
    ld1=0
    if(type(sr1)==float):
      ld1=len(str(sr1))
    elif(type(sr1)==int):
      ld1=len(str(sr1))
    else:
      ld1 = len(sr1) 
    len_dom.append(ld1)        

#ip or domain
ip_dom= []   
for i in range(1,rows):
    ur1=list1[i][0]
    if(type(ur1)==float):
        ip_dom.append(1)
    else:
        ip_dom.append(0)           
       
# Setting Path of File and Initializing List:
location = ("UNB_binary_full.xlsx") 
ful_list = []

# Opening the Workbook and Defining Which Sheet to Use:
wb = xlrd.open_workbook(location) 
sheet = wb.sheet_by_index(0) 

# Starting at Row 0 and Column 0:
sheet.cell_value(0, 0)

# Iterating Over the Number of Rows and Appending to List:
for i in range(0, rows):
    ful_list.append(sheet.row_values(i))

dots=[]
slash=[]
spcl=[]
exe=[]


for i in range(1,rows):
    dt = ful_list[i][0].count(".")
    dots.append(dt)

for i in range(1,rows):
    ss = ful_list[i][0].count("/")
    slash.append(ss)

for i in range(1,rows):
    exe_count=0
    ex = ful_list[i][0].count("exe")
    exe_count = exe_count+ex
    ins = ful_list[i][0].count("install")
    exe_count = exe_count+ins
    exe.append(exe_count)
    
tempt=[]    
for i in range(1,rows):
    temp_count=0
    temp1 = ful_list[i][0].count("free")
    temp_count= temp_count+temp1
    temp2 = ful_list[i][0].count("money")
    temp_count= temp_count+temp2
    temp3 = ful_list[i][0].count("best")
    temp_count= temp_count+temp3
    temp4 = ful_list[i][0].count("game")
    temp_count= temp_count+temp4
    tempt.append(temp_count)

https=[]
for i in range(1,rows):
    htt1 = ful_list[i][0].count("https")
    https.append(htt1)  

htmlt=[]
for i in range(1,rows):
    ht_count=0
    ht1=ful_list[i][0].count(".htm")
    ht_count=ht_count+ht1
    ht2=ful_list[i][0].count(".html")
    ht_count=ht_count+ht2
    htmlt.append(ht_count)

php=[]
for i in range(1,rows):
    ph1 = ful_list[i][0].count(".php")
    php.append(ph1)
    
com=[]
for i in range(1,rows):
    co1 = ful_list[i][0].count(".com")
    com.append(co1)
    
gov=[]
for i in range(1,rows):
    go1 = ful_list[i][0].count(".gov")
    gov.append(go1)
    
edu=[]
for i in range(1,rows):
    ed1 = ful_list[i][0].count(".edu")
    edu.append(ed1)
    
org=[]
for i in range(1,rows):
    or1 = ful_list[i][0].count(".org")
    org.append(or1)
    
text=[]
for i in range(1,rows):
    tx = ful_list[i][0].count(".txt")
    text.append(tx)

net=[]
for i in range(1,rows):
    nt = ful_list[i][0].count(".net")
    net.append(nt)

info=[]
for i in range(1,rows):
    inf = ful_list[i][0].count(".info")
    info.append(inf)
    
js=[]
for i in range(1,rows):    
    js1 = ful_list[i][0].count(".js")
    js.append(js1)
    
offens=[]
for i in range(1,rows): 
    offens_count=0
    off1 = ful_list[i][0].count("girl")
    offens_count=offens_count+off1
    off2 = ful_list[i][0].count("hot")
    offens_count=offens_count+off2
    off3 = ful_list[i][0].count("nude")
    offens_count=offens_count+off3
    off4 = ful_list[i][0].count("ball")
    offens_count=offens_count+off4
    off5 = ful_list[i][0].count("sex")
    offens_count=offens_count+off5
    off6 = ful_list[i][0].count("fuck")
    offens_count=offens_count+off6
    off7 = ful_list[i][0].count("xx")
    offens_count=offens_count+off7
    offens.append(offens_count)

qs_mark=[]
for i in range(1,rows):    
    qs = ful_list[i][0].count("?")
    qs_mark.append(qs)
    
    
for i in range(1,rows):
    sp_count=0
    sp1=ful_list[i][0].count("@")
    sp_count=sp_count+sp1
    sp2=ful_list[i][0].count("_")
    sp_count=sp_count+sp2
    sp3=ful_list[i][0].count("=")
    sp_count=sp_count+sp3
    sp4=ful_list[i][0].count("#")
    sp_count=sp_count+sp4
    sp5=ful_list[i][0].count("&")
    sp_count=sp_count+sp5
    sp6=ful_list[i][0].count("!")
    sp_count=sp_count+sp6
    sp7=ful_list[i][0].count("$")
    sp_count=sp_count+sp7
    sp8=ful_list[i][0].count("%")
    sp_count=sp_count+sp8
    sp9=ful_list[i][0].count("^")
    sp_count=sp_count+sp9
    sp10=ful_list[i][0].count("*")
    sp_count=sp_count+sp10
    sp11=ful_list[i][0].count("^")
    sp_count=sp_count+sp11
    sp12=ful_list[i][0].count("*")
    sp_count=sp_count+sp12
    sp13=ful_list[i][0].count("-")
    sp_count=sp_count+sp13
    sp14=ful_list[i][0].count("+")
    sp_count=sp_count+sp14
    spcl.append(sp_count)

watch=[]
for i in range(1,rows):
    wat = ful_list[i][0].count("watch")
    watch.append(wat)
    
youtube=[]
for i in range(1,rows):
    you = ful_list[i][0].count("youtube")
    youtube.append(you)
    
image=[]
for i in range(1,rows):
    ima = ful_list[i][0].count("image")
    image.append(ima)

login_upload=[]
for i in range(1,rows): 
    login_count=0
    log1 = ful_list[i][0].count("login")
    login_count=login_count+log1
    log2 = ful_list[i][0].count("upload")
    login_count=login_count+log2
    login_upload.append(login_count)
    
# no of digits count
num_count=[]
for i in range(1,rows):
    digi=alfa=0
    ulstr=ful_list[i][0]
    for c in ulstr:
        if c.isdigit():
            digi=digi+1
        else:
            pass
    num_count.append(digi)
    
url_len=[]
for i in range(1,rows):
    ul = len(ful_list[i][0])
    url_len.append(ul)     


bad_count=0
good_count=0
#class values    
url_class = []
for i in range(1,rows):
    url_cls = ful_list[i][1]
    if(url_cls=='malicious'): 
        url_class.append(1)
        bad_count=bad_count+1
    else:
        url_class.append(0)
        good_count=good_count+1

print("Total Legimate URLs: ",good_count)
print("Total Malicious URLs: ",bad_count)



testing......
Total Legimate URLs:  35378
Total Malicious URLs:  129988
(165366, 28)


In [ ]:
#dataframe
data=pd.DataFrame(
    {'url_len': url_len,
     'maxw_len': maxl,
     'dots': dots,
     'domain_len' : len_dom,
     'numeric_count': num_count,
     'no_/' : slash,
     'spcl_char': spcl,
     '.exe_install': exe,
     '.com': com,
     '.php': php,
     '.gov': gov,
     '.org': org,
     '.edu': edu,
     'https': https,
     '.htm_html': htmlt,
     #'.txt': text,
     '.net': net,
     '.info': info,
     '.js': js,
     'q_?': qs_mark,
     'tempt_word' : tempt,
     'offensive': offens,
     #'watch': watch,
     'youtube': youtube,
     #'image': image,
     'login_upload' :login_upload,
     'IP' : ip_dom,
     'URL_Class': url_class
     
    })



data_sape=data.shape
print(data_sape)


X = data.iloc[:, 0:(data_sape[1]-1)].values
y = data.iloc[:, (data_sape[1]-1)].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)



(165366, 25)


In [ ]:
#y_train
TR_bad_count=0
TR_good_count=0
for i in range(0,len(y_train)):
    cls = y_train[i]
    if(cls==1): 
      TR_bad_count=TR_bad_count+1
    else:
      TR_good_count=TR_good_count+1
print("Total dataset : ",len(data))
print("Total training dataset : ",len(y_train))
print("Total Legimate URLs training dataset : ",TR_good_count)
print("Total Malicious URLs training dataset: ",TR_bad_count)


#y_test
TE_bad_count=0
TE_good_count=0
for i in range(0,len(y_test)):
    cls = y_test[i]
    if(cls==1): 
      TE_bad_count=TE_bad_count+1
    else:
      TE_good_count=TE_good_count+1

print("Total testing dataset : ",len(y_test))
print("Total Legimate URLs testing dataset : ",TE_good_count)
print("Total Malicious URLs testing dataset: ",TE_bad_count)

Total dataset :  165366
Total training dataset :  132292
Total Legimate URLs training dataset :  28240
Total Malicious URLs training dataset:  104052
Total testing dataset :  33074
Total Legimate URLs testing dataset :  7138
Total Malicious URLs testing dataset:  25936


In [ ]:
#SVM

# Load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

#Gaussian Kernel
svclassifier = SVC(kernel='rbf')
svclassifier.fit(x_train, y_train)
y_pred = svclassifier.predict(x_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Accuracy: 0.9799842776803531
[[ 6875   237]
 [  425 25537]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.95      7112
           1       0.99      0.98      0.99     25962

    accuracy                           0.98     33074
   macro avg       0.97      0.98      0.97     33074
weighted avg       0.98      0.98      0.98     33074



In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

#target_names = ['True', 'False']
print(classification_report(y_test, y_pred))

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# Creating the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7138
           1       1.00      1.00      1.00     25936

    accuracy                           0.99     33074
   macro avg       0.99      0.99      0.99     33074
weighted avg       0.99      0.99      0.99     33074

Accuracy: 0.9947390699643224
[[ 7049    89]
 [   85 25851]]


In [ ]:
#LogisticRegression

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
 

logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)
 
predictions = logmodel.predict(x_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       0.84      0.79      0.82      7112
           1       0.94      0.96      0.95     25962

    accuracy                           0.92     33074
   macro avg       0.89      0.88      0.88     33074
weighted avg       0.92      0.92      0.92     33074

[[ 5649  1463]
 [ 1054 24908]]
0.9238979258632158


In [ ]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=50)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)


#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

target_names = ['True', 'False']
print(classification_report(y_test, y_pred, target_names=target_names))


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# Creating the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
cm


              precision    recall  f1-score   support

        True       0.99      0.99      0.99      7112
       False       1.00      1.00      1.00     25962

    accuracy                           1.00     33074
   macro avg       1.00      1.00      1.00     33074
weighted avg       1.00      1.00      1.00     33074

Accuracy: 0.9972788292918909


array([[ 7073,    39],
       [   51, 25911]])

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

optimizer1=keras.optimizers.Adam(lr=0.002)
#create model
model = Sequential()

#get number of columns in training data
n_cols = x_train.shape[1]


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)


#create model
model_mc = Sequential()

#add model layers
model_mc.add(Dense(27, activation='relu', input_shape=(n_cols,)))
model_mc.add(Dense(32, activation='relu'))
model_mc.add(Dense(32, activation='relu'))
model_mc.add(Dense(32, activation='relu'))
model_mc.add(Dense(32, activation='relu'))
model_mc.add(Dense(1))

#compile model using mse as a measure of model performance
model_mc.compile(optimizer='adam', loss='mean_squared_error')

#train model
model_mc.fit(x_train, y_train, validation_split=0.2, epochs=300, callbacks=[early_stopping_monitor])
#model_mc.fit(x_train, y_train, validation_split=0.2, epochs=30)



# Predicting the Test set results
y_pred = model_mc.predict(x_test)
y_pred = (y_pred > 0.5)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


print(classification_report(y_test, y_pred))

# Creating the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
cm

Epoch 1/300
3308/3308 [==============================] - 5s 1ms/step - loss: 0.0348 - val_loss: 0.0193
Epoch 2/300
3308/3308 [==============================] - 4s 1ms/step - loss: 0.0139 - val_loss: 0.0124
Epoch 3/300
3308/3308 [==============================] - 4s 1ms/step - loss: 0.0109 - val_loss: 0.0108
Epoch 4/300
3308/3308 [==============================] - 5s 1ms/step - loss: 0.0094 - val_loss: 0.0090
Epoch 5/300
3308/3308 [==============================] - 4s 1ms/step - loss: 0.0082 - val_loss: 0.0088
Epoch 6/300
3308/3308 [==============================] - 4s 1ms/step - loss: 0.0077 - val_loss: 0.0081
Epoch 7/300
3308/3308 [==============================] - 5s 1ms/step - loss: 0.0068 - val_loss: 0.0072
Epoch 8/300
3308/3308 [==============================] - 4s 1ms/step - loss: 0.0064 - val_loss: 0.0075
Epoch 9/300
3308/3308 [==============================] - 5s 1ms/step - loss: 0.0059 - val_loss: 0.0074
Epoch 10/300
3308/3308 [==============================] - 4s 1ms/step - l

array([[ 7049,    63],
       [  100, 25862]])