In [ ]:
import xlrd 
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import matplotlib.pyplot as plt
import keras
#from keras.datasets import mnist
from keras.models import Sequential,model_from_json
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop
import pylab as plt



# Setting Path of File and Initializing List:
location = ("UNB_multi_sep.xlsx") 
list1 = []

# Opening the Workbook and Defining Which Sheet to Use:
wb = xlrd.open_workbook(location) 
sheet = wb.sheet_by_index(0) 

# Starting at Row 0 and Column 0:
sheet.cell_value(0, 0)

rows, cols = (165367, 9) 

# Iterating Over the Number of Rows and Appending to List:
for i in range(0, rows):
    list1.append(sheet.row_values(i))



#maximum lengh of word in list in every row 
maxl = []
for i in range(1,rows):
    max1=0
    for j in range(cols):
        sr1=list1[i][j]
        if(type(sr1)==float):
          max1=1
        elif(type(sr1)==int):
          max1=1 
        else:
            ml1=len(list1[i][j])
            if(ml1>max1):
                max1=ml1 
    maxl.append(max1)

#length of domain name
len_dom= []
for i in range(1,rows):
    sr1=list1[i][1]
    ld1=0
    if(type(sr1)==float):
      ld1=len(str(sr1))
    elif(type(sr1)==int):
      ld1=len(str(sr1))
    else:
      ld1 = len(sr1) 
    len_dom.append(ld1)        

#ip or domain
ip_dom= []   
for i in range(1,rows):
    ur1=list1[i][0]
    if(type(ur1)==float):
        ip_dom.append(1)
    else:
        ip_dom.append(0)           
    
   
# Setting Path of File and Initializing List:
location = ("UNB_multi_full.xlsx") 
ful_list = []

# Opening the Workbook and Defining Which Sheet to Use:
wb = xlrd.open_workbook(location) 
sheet = wb.sheet_by_index(0) 

# Starting at Row 0 and Column 0:
sheet.cell_value(0, 0)

# Iterating Over the Number of Rows and Appending to List:
for i in range(0, rows):
    ful_list.append(sheet.row_values(i))

dots=[]
slash=[]
spcl=[]
exe=[]


for i in range(1,rows):
    dt = ful_list[i][0].count(".")
    dots.append(dt)

for i in range(1,rows):
    ss = ful_list[i][0].count("/")
    slash.append(ss)

for i in range(1,rows):
    exe_count=0
    ex = ful_list[i][0].count("exe")
    exe_count = exe_count+ex
    ins = ful_list[i][0].count("install")
    exe_count = exe_count+ins
    exe.append(exe_count)
    
tempt=[]    
for i in range(1,rows):
    temp_count=0
    temp1 = ful_list[i][0].count("free")
    temp_count= temp_count+temp1
    temp2 = ful_list[i][0].count("money")
    temp_count= temp_count+temp2
    temp3 = ful_list[i][0].count("best")
    temp_count= temp_count+temp3
    temp4 = ful_list[i][0].count("game")
    temp_count= temp_count+temp4
    tempt.append(temp_count)

https=[]
for i in range(1,rows):
    htt1 = ful_list[i][0].count("https")
    https.append(htt1)  

htmlt=[]
for i in range(1,rows):
    ht_count=0
    ht1=ful_list[i][0].count(".htm")
    ht_count=ht_count+ht1
    ht2=ful_list[i][0].count(".html")
    ht_count=ht_count+ht2
    htmlt.append(ht_count)

php=[]
for i in range(1,rows):
    ph1 = ful_list[i][0].count(".php")
    php.append(ph1)
    
com=[]
for i in range(1,rows):
    co1 = ful_list[i][0].count(".com")
    com.append(co1)
    
gov=[]
for i in range(1,rows):
    go1 = ful_list[i][0].count(".gov")
    gov.append(go1)
    
edu=[]
for i in range(1,rows):
    ed1 = ful_list[i][0].count(".edu")
    edu.append(ed1)
    
org=[]
for i in range(1,rows):
    or1 = ful_list[i][0].count(".org")
    org.append(or1)
    
text=[]
for i in range(1,rows):
    tx = ful_list[i][0].count(".txt")
    text.append(tx)

net=[]
for i in range(1,rows):
    nt = ful_list[i][0].count(".net")
    net.append(nt)

info=[]
for i in range(1,rows):
    inf = ful_list[i][0].count(".info")
    info.append(inf)
    
js=[]
for i in range(1,rows):    
    js1 = ful_list[i][0].count(".js")
    js.append(js1)
    
offens=[]
for i in range(1,rows): 
    offens_count=0
    off1 = ful_list[i][0].count("girl")
    offens_count=offens_count+off1
    off2 = ful_list[i][0].count("hot")
    offens_count=offens_count+off2
    off3 = ful_list[i][0].count("nude")
    offens_count=offens_count+off3
    off4 = ful_list[i][0].count("ball")
    offens_count=offens_count+off4
    off5 = ful_list[i][0].count("sex")
    offens_count=offens_count+off5
    off6 = ful_list[i][0].count("fuck")
    offens_count=offens_count+off6
    off7 = ful_list[i][0].count("xx")
    offens_count=offens_count+off7
    offens.append(offens_count)

qs_mark=[]
for i in range(1,rows):    
    qs = ful_list[i][0].count("?")
    qs_mark.append(qs)
    
    
for i in range(1,rows):
    sp_count=0
    sp1=ful_list[i][0].count("@")
    sp_count=sp_count+sp1
    sp2=ful_list[i][0].count("_")
    sp_count=sp_count+sp2
    sp3=ful_list[i][0].count("=")
    sp_count=sp_count+sp3
    sp4=ful_list[i][0].count("#")
    sp_count=sp_count+sp4
    sp5=ful_list[i][0].count("&")
    sp_count=sp_count+sp5
    sp6=ful_list[i][0].count("!")
    sp_count=sp_count+sp6
    sp7=ful_list[i][0].count("$")
    sp_count=sp_count+sp7
    sp8=ful_list[i][0].count("%")
    sp_count=sp_count+sp8
    sp9=ful_list[i][0].count("^")
    sp_count=sp_count+sp9
    sp10=ful_list[i][0].count("*")
    sp_count=sp_count+sp10
    sp11=ful_list[i][0].count("^")
    sp_count=sp_count+sp11
    sp12=ful_list[i][0].count("*")
    sp_count=sp_count+sp12
    sp13=ful_list[i][0].count("-")
    sp_count=sp_count+sp13
    sp14=ful_list[i][0].count("+")
    sp_count=sp_count+sp14
    spcl.append(sp_count)

watch=[]
for i in range(1,rows):
    wat = ful_list[i][0].count("watch")
    watch.append(wat)
    
youtube=[]
for i in range(1,rows):
    you = ful_list[i][0].count("youtube")
    youtube.append(you)
    
image=[]
for i in range(1,rows):
    ima = ful_list[i][0].count("image")
    image.append(ima)

login_upload=[]
for i in range(1,rows): 
    login_count=0
    log1 = ful_list[i][0].count("login")
    login_count=login_count+log1
    log2 = ful_list[i][0].count("upload")
    login_count=login_count+log2
    login_upload.append(login_count)
    
# no of digits count
num_count=[]
for i in range(1,rows):
    digi=alfa=0
    ulstr=ful_list[i][0]
    for c in ulstr:
        if c.isdigit():
            digi=digi+1
        else:
            pass
    num_count.append(digi)
    
url_len=[]
for i in range(1,rows):
    ul = len(ful_list[i][0])
    url_len.append(ul)     

#class values    
url_class = []
for i in range(1,rows):
    url_cls = ful_list[i][1]
    if(url_cls=='benign'): 
        url_class.append(1)
    elif(url_cls=='phishing'): 
        url_class.append(2)
    elif(url_cls=='malware'): 
        url_class.append(3)
    elif(url_cls=='spam'): 
        url_class.append(4)
    else:
        url_class.append(5)



In [ ]:
#dataframe
data=pd.DataFrame(
    {'url_len': url_len,
     'maxw_len': maxl,
     'dots': dots,
     'domain_len' : len_dom,
     'numeric_count': num_count,
     'no_/' : slash,
     'spcl_char': spcl,
     '.exe_install': exe,
     '.com': com,
     '.php': php,
     '.gov': gov,
     '.org': org,
     '.edu': edu,
     'https': https,
     '.htm_html': htmlt,
     #'.txt': text,
     '.net': net,
     '.info': info,
     '.js': js,
     'q_?': qs_mark,
     'tempt_word' : tempt,
     'offensive': offens,
     #'watch': watch,
     #'youtube': youtube,
     'image': image,
     'login_upload' :login_upload,
     'IP' : ip_dom,
     'URL_Class': url_class
     
    })




data_shape=data.shape
print(data_shape)


X = data.iloc[:, 0:(data_shape[1]-1)].values
y = data.iloc[:, (data_shape[1]-1)].values


# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


(165366, 25)


In [ ]:
#KNN
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.neighbors import KNeighborsClassifier


classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

#target_names = ['True', 'False']
print(classification_report(y_test, y_pred))

# Creating the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9719417064763863
              precision    recall  f1-score   support

           1       0.98      0.99      0.98      6972
           2       0.94      0.78      0.85      2075
           3       0.95      0.96      0.96      2301
           4       0.96      0.97      0.97      2325
           5       0.97      0.99      0.98     19401

    accuracy                           0.97     33074
   macro avg       0.96      0.94      0.95     33074
weighted avg       0.97      0.97      0.97     33074

[[ 6881     7    26     8    50]
 [   39  1621    36    27   352]
 [   23    27  2213     5    33]
 [    5     7     3  2251    59]
 [   65    68    41    47 19180]]
Accuracy: 0.9719417064763863


In [ ]:
import os
from glob import glob
import matplotlib.pyplot as plt
import random
import cv2
import pandas as pd
import numpy as np
import matplotlib.gridspec as gridspec
import seaborn as sns
import zlib
import itertools
import sklearn
import itertools
import scipy
import skimage
from skimage.transform import resize
import csv
from tqdm import tqdm
from sklearn import model_selection
from sklearn.model_selection import train_test_split, learning_curve,KFold,cross_val_score,StratifiedKFold
from sklearn.utils import class_weight
from sklearn.metrics import confusion_matrix
import keras
from keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D, Lambda, MaxPool2D, BatchNormalization
from keras.utils import np_utils
from keras.utils.np_utils import to_categorical
from keras.preprocessing.image import ImageDataGenerator
from keras import models, layers, optimizers
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.utils import class_weight
from keras.optimizers import SGD, RMSprop, Adam, Adagrad, Adadelta, RMSprop
from keras.models import Sequential, model_from_json
from keras.layers import Activation,Dense, Dropout, Flatten, Conv2D, MaxPool2D,MaxPooling2D,AveragePooling2D, BatchNormalization
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ReduceLROnPlateau, ModelCheckpoint
from keras import backend as K
from keras.applications.vgg16 import VGG16
from keras.models import Model
from keras.applications.inception_v3 import InceptionV3
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
#from keras.applications.mobilenet import MobileNet
#from sklearn.metrics import roc_auc_score
#from sklearn.metrics import roc_curve
#from sklearn.metrics import auc

In [ ]:
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

# encode class values as integers
encoder = LabelEncoder()
encoder.fit(y)
encoded_Y = encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

encoder.fit(y_train)
encoded_Ytrain = encoder.transform(y_train)
# convert integers to dummy variables (i.e. one hot encoded)
dy_train = np_utils.to_categorical(encoded_Ytrain)

encoder.fit(y_test)
encoded_Ytest = encoder.transform(y_test)
# convert integers to dummy variables (i.e. one hot encoded)
dy_test = np_utils.to_categorical(encoded_Ytest)


In [ ]:

from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


optimizer1=keras.optimizers.Adam(lr=0.002)
#create model
model = Sequential()

#get number of columns in training data
n_cols = x_train.shape[1]


from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=10)


#create model
model_mc = Sequential()

#add model layers
model_mc.add(Dense(27, activation='relu', input_shape=(n_cols,)))
model_mc.add(Dense(32, activation='relu'))
model_mc.add(Dense(32, activation='relu'))
model_mc.add(Dense(32, activation='relu'))
model_mc.add(Dense(32, activation='relu'))
model_mc.add(Dense(5, activation='softmax'))

#compile model using mse as a measure of model performance
model_mc.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

#train model
model_mc.fit(x_train, dy_train, validation_split=0.2, epochs=300, callbacks=[early_stopping_monitor])
#model_mc.fit(x_train, y_train, validation_split=0.2, epochs=30)

model_mc.summary()


y_pred = model_mc.predict(x_test)
Y_pred_classes = np.argmax(y_pred,axis = 1) 
Y_true = np.argmax(dy_test,axis = 1) 


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_true, Y_pred_classes))

#target_names = ['True', 'False']
print(classification_report(Y_true, Y_pred_classes))


print(confusion_matrix(Y_true, Y_pred_classes))

Epoch 1/300
3308/3308 [==============================] - 5s 2ms/step - loss: 0.0382 - accuracy: 0.8787 - val_loss: 0.0288 - val_accuracy: 0.9074
Epoch 2/300
3308/3308 [==============================] - 5s 1ms/step - loss: 0.0250 - accuracy: 0.9224 - val_loss: 0.0230 - val_accuracy: 0.9303
Epoch 3/300
3308/3308 [==============================] - 5s 1ms/step - loss: 0.0217 - accuracy: 0.9332 - val_loss: 0.0196 - val_accuracy: 0.9403
Epoch 4/300
3308/3308 [==============================] - 5s 2ms/step - loss: 0.0196 - accuracy: 0.9397 - val_loss: 0.0184 - val_accuracy: 0.9438
Epoch 5/300
3308/3308 [==============================] - 5s 2ms/step - loss: 0.0184 - accuracy: 0.9443 - val_loss: 0.0193 - val_accuracy: 0.9411
Epoch 6/300
3308/3308 [==============================] - 5s 2ms/step - loss: 0.0175 - accuracy: 0.9469 - val_loss: 0.0175 - val_accuracy: 0.9464
Epoch 7/300
3308/3308 [==============================] - 5s 1ms/step - loss: 0.0170 - accuracy: 0.9488 - val_loss: 0.0176 - val_ac

In [ ]:
#LogisticRegression

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
 

logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)
 
predictions = logmodel.predict(x_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           1       0.83      0.87      0.85      6972
           2       0.80      0.40      0.53      2075
           3       0.82      0.51      0.63      2301
           4       0.73      0.73      0.73      2325
           5       0.87      0.94      0.91     19401

    accuracy                           0.85     33074
   macro avg       0.81      0.69      0.73     33074
weighted avg       0.85      0.85      0.84     33074

[[ 6067    11    77    95   722]
 [  145   823    58   168   881]
 [  449    92  1168    53   539]
 [   66     1     2  1686   570]
 [  550   102   119   318 18312]]
0.8482796154078732


In [ ]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=20)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)


#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

#target_names = ['True', 'False']
print(classification_report(y_test, y_pred))


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

# Creating the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

              precision    recall  f1-score   support

           1       0.99      1.00      0.99      6972
           2       0.95      0.79      0.87      2075
           3       0.99      0.97      0.98      2301
           4       0.98      0.97      0.97      2325
           5       0.97      0.99      0.98     19401

    accuracy                           0.98     33074
   macro avg       0.98      0.94      0.96     33074
weighted avg       0.98      0.98      0.98     33074

Accuracy: 0.9775352240430549
[[ 6940     2     2     1    27]
 [   17  1642     7     7   402]
 [   13    13  2232     0    43]
 [    1    11     1  2248    64]
 [   32    52     5    43 19269]]


In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

#Gaussian Kernel
svclassifier = SVC(kernel='rbf')
svclassifier.fit(x_train, y_train)
y_pred = svclassifier.predict(x_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9286750922174518
[[ 6815    13    16    16   112]
 [   41  1153    28    24   829]
 [  194    65  1713    35   294]
 [   17     8     2  1978   320]
 [  211    58    20    56 19056]]
              precision    recall  f1-score   support

           1       0.94      0.98      0.96      6972
           2       0.89      0.56      0.68      2075
           3       0.96      0.74      0.84      2301
           4       0.94      0.85      0.89      2325
           5       0.92      0.98      0.95     19401

    accuracy                           0.93     33074
   macro avg       0.93      0.82      0.86     33074
weighted avg       0.93      0.93      0.92     33074

